name: PowerShell Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PowerShell
        uses: actions/setup-powershell@v2

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: Install-Module PSScriptAnalyzer -Force -Scope CurrentUser

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path ./scripts -Recurse -Severity Warning -OutVariable results
          if ($results.Count -gt 0) {
            $results | Format-Table -AutoSize
          }
