name: PowerShell Lint

on:
  push:
  pull_request:

jobs:
  lint:
    # Use windows-2022 to avoid the windows-latest migration for now.
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: Install-Module PSScriptAnalyzer -Force -Scope CurrentUser

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          $results = Invoke-ScriptAnalyzer -Path ./scripts -Recurse -Severity Warning
          if ($results) {
            $results | Format-Table -AutoSize
            throw "PSScriptAnalyzer found issues."
          }
